---
# tasks file for app


- name: Upload static site tarball
  copy:
    src: static-site.tar.gz
    dest: /var/www/

- name: Extract tarball
  shell: tar -xvf /var/www/static-site.tar.gz


- name: Permission
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
