---
# tasks file for ssh

- name: Copy the files
  copy:
    src: /home/sid/.ssh/authorized_keys
    dest: /home/{{ ansible_user }}/.ssh/authorized_keys
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600' 
